export const TRANSLATION = 'TRANSLATION';
export const TRANSLATION_STARTED = 'TRANSLATION_STARTED';
export const TRANSLATION_SUCCEEDED = 'TRANSLATION_SUCCEEDED';
export const TRANSLATION_FAILED = 'TRANSLATION_FAILED';
export const TRANSLATION_ENDED = 'TRANSLATION_ENDED';
