export const ADD_TODO = 'ADD_TODO';
export const EDIT_TODO = 'EDIT_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const COMPLETE_TODO = 'COMPLETE_TODO';
export const COMPLETE_ALL = 'COMPLETE_ALL';
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED';

export const TRANSLATION = 'TRANSLATION';
export const TRANSLATION_STARTED = 'TRANSLATION_STARTED';
export const TRANSLATION_SUCCEEDED = 'TRANSLATION_SUCCEEDED';
export const TRANSLATION_FAILED = 'TRANSLATION_FAILED';
export const TRANSLATION_ENDED = 'TRANSLATION_ENDED';
